/*
  MonaV2_lib.cpp - Implementation of the library for MonaV2 robot
  Created by Bart Garcia, November 2019.
  bart.garcia.nathan@gmail.com
  Released into the public domain.
*/
#include "MonaV2_lib.h"

/* ----Library functions implementation for MonaV2 in C style----*/
//Mona Init function - setup pinModes
void MonaV2_init(void){
	//Set PinModes
	pinMode(Mot_right_forward, OUTPUT);		//Motor control outputs
	pinMode(Mot_right_backward, OUTPUT);	//Motor control outputs
	pinMode(Mot_left_forward, OUTPUT);		//Motor control outputs
	pinMode(Mot_left_backward, OUTPUT);		//Motor control outputs
	pinMode(Mot_right_feedback, INPUT);		//Motor feedback inputs
	pinMode(Mot_left_feedback, INPUT);		//Motor feedback inputs
	pinMode(IR_enable, OUTPUT);				//IR enable output
	pinMode(LED_D2, OUTPUT);				//LED output
	pinMode(LED_D3, OUTPUT);				//LED output
	//Turn off the Motor
    digitalWrite(Mot_right_forward,LOW);
    digitalWrite(Mot_right_backward,LOW);
    digitalWrite(Mot_left_forward,LOW);
    digitalWrite(Mot_left_backward,LOW);
    //Disable IR to save energy
    digitalWrite(IR_enable,LOW);
    //Turn OFF LEDs
    digitalWrite(LED_D2,LOW);
    digitalWrite(LED_D3,LOW);
}
//TODO : Add PWM values to the motor speeds
//Right Motor
void Right_mot_forward(void){
	digitalWrite(Mot_right_forward,HIGH);
    digitalWrite(Mot_right_backward,LOW);
}

void Right_mot_backward(void){
	digitalWrite(Mot_right_forward,LOW);
    digitalWrite(Mot_right_backward,HIGH);
}

void Right_mot_stop(void){
	digitalWrite(Mot_right_forward,LOW);
    digitalWrite(Mot_right_backward,LOW);
}
//Left Motor
void Left_mot_forward(void){
	digitalWrite(Mot_left_forward,HIGH);
    digitalWrite(Mot_left_backward,LOW);
}

void Left_mot_backward(void){
	digitalWrite(Mot_left_forward,LOW);
    digitalWrite(Mot_left_backward,HIGH);
}
void Left_mot_stop(void){
	digitalWrite(Mot_left_forward,LOW);
    digitalWrite(Mot_left_backward,LOW);
}

//Both motors
void Motors_forward(void){
	Right_mot_forward();
	Left_mot_forward();
}

void Motors_backward(void){
	Right_mot_backward();
	Left_mot_backward();
}

void Motors_stop(void){
	Right_mot_stop();
	Left_mot_stop();
}

//IR sensors
void Enable_IR(void){
	digitalWrite(IR_enable,HIGH);
}

void Disable_IR(void){
	digitalWrite(IR_enable,LOW);
}

int Read_IR(int IR_number){
	if (IR_number>= 1 && IR_number<6){ //Ensure the IR number is within range
		if(IR_number==1){
			return analogRead(IR1_sensor);//Return value for IR1_sensor
		}
		if(IR_number==2){
			return analogRead(IR2_sensor);//Return value for IR2_sensor
		}
		if(IR_number==3){
			return analogRead(IR3_sensor);//Return value for IR3_sensor
		}
		if(IR_number==4){
			return analogRead(IR4_sensor);//Return value for IR4_sensor
		}
		if(IR_number==5){
			return analogRead(IR5_sensor);//Return value for IR5_sensor
		}
	}
	else {
		return 0; // Return a 0 as an error
	}
}

//Battery Voltage
int Batt_Vol(void){
	return analogRead(Batt_Vol_pin);
	//TODO : Add here the conversion to the ratio generated by the Resistors
}

//LEDS control
//TODO : Add PWM values to the LEDs
void LED2_ON(void){
	digitalWrite(LED_D2,HIGH);	
}

void LED2_OFF(void){
	digitalWrite(LED_D2,LOW);
}

void LED3_ON(void){
	digitalWrite(LED_D3,HIGH);	
}

void LED3_OFF(void){
	digitalWrite(LED_D3,LOW);
}

/* ----Library interface implementation for MonaV2 in Arduino Library style----*/
//MonaV2 constructor, set up Pinmodes
MonaV2::MonaV2(void){
  //Set PinModes
	pinMode(Mot_right_forward, OUTPUT);		//Motor control outputs
	pinMode(Mot_right_backward, OUTPUT);	//Motor control outputs
	pinMode(Mot_left_forward, OUTPUT);		//Motor control outputs
	pinMode(Mot_left_backward, OUTPUT);		//Motor control outputs
	pinMode(Mot_right_feedback, INPUT);		//Motor feedback inputs
	pinMode(Mot_left_feedback, INPUT);		//Motor feedback inputs
	pinMode(IR_enable, OUTPUT);				//IR enable output
	pinMode(LED_D2, OUTPUT);				//LED output
	pinMode(LED_D3, OUTPUT);				//LED output
	//Turn off the Motor
    digitalWrite(Mot_right_forward,LOW);
    digitalWrite(Mot_right_backward,LOW);
    digitalWrite(Mot_left_forward,LOW);
    digitalWrite(Mot_left_backward,LOW);
    //Disable IR to save energy
    digitalWrite(IR_enable,LOW);
    //Turn OFF LEDs
    digitalWrite(LED_D2,LOW);
    digitalWrite(LED_D3,LOW);
}
//TODO : Add PWM values to the motor speeds
//Right Motor
void MonaV2::Right_mot_forward(void){
	digitalWrite(Mot_right_forward,HIGH);
    digitalWrite(Mot_right_backward,LOW);
}

void MonaV2::Right_mot_backward(void){
	digitalWrite(Mot_right_forward,LOW);
    digitalWrite(Mot_right_backward,HIGH);
}

void MonaV2::Right_mot_stop(void){
	digitalWrite(Mot_right_forward,LOW);
    digitalWrite(Mot_right_backward,LOW);
}
//Left Motor
void MonaV2::Left_mot_forward(void){
	digitalWrite(Mot_left_forward,HIGH);
    digitalWrite(Mot_left_backward,LOW);
}

void MonaV2::Left_mot_backward(void){
	digitalWrite(Mot_left_forward,LOW);
    digitalWrite(Mot_left_backward,HIGH);
}
void MonaV2::Left_mot_stop(void){
	digitalWrite(Mot_left_forward,LOW);
    digitalWrite(Mot_left_backward,LOW);
}

//Both motors
void MonaV2::Motors_forward(void){
	Right_mot_forward();
	Left_mot_forward();
}

void MonaV2::Motors_backward(void){
	Right_mot_backward();
	Left_mot_backward();
}

void MonaV2::Motors_stop(void){
	Right_mot_stop();
	Left_mot_stop();
}

//IR sensors
void MonaV2::Enable_IR(void){
	digitalWrite(IR_enable,HIGH);
}

void MonaV2::Disable_IR(void){
	digitalWrite(IR_enable,LOW);
}

int MonaV2::Read_IR(int IR_number){
	if (IR_number>= 1 && IR_number<6){ //Ensure the IR number is within range
		if(IR_number==1){
			return analogRead(IR1_sensor);//Return value for IR1_sensor
		}
		if(IR_number==2){
			return analogRead(IR2_sensor);//Return value for IR2_sensor
		}
		if(IR_number==3){
			return analogRead(IR3_sensor);//Return value for IR3_sensor
		}
		if(IR_number==4){
			return analogRead(IR4_sensor);//Return value for IR4_sensor
		}
		if(IR_number==5){
			return analogRead(IR5_sensor);//Return value for IR5_sensor
		}
	}
	else {
		return 0; // Return a 0 as an error
	}
}

//Battery Voltage
int MonaV2::Batt_Vol(void){
	return analogRead(Batt_Vol_pin);
	//TODO : Add here the conversion to the ratio generated by the Resistors
}

//LEDS control
//TODO : Add PWM values to the LEDs
void MonaV2::LED2_ON(void){
	digitalWrite(LED_D2,HIGH);	
}

void MonaV2::LED2_OFF(void){
	digitalWrite(LED_D2,LOW);
}

void MonaV2::LED3_ON(void){
	digitalWrite(LED_D3,HIGH);	
}

void MonaV2::LED3_OFF(void){
	digitalWrite(LED_D3,LOW);
}
